#!/bin/bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Mozilla Foundation
# Build the pdfium PDF renderer wasm.
#
# pdfium has no upstream emscripten target, so this script:
#   1. Clones pdfium + abseil + fast_float (via gclient-less manual fetch)
#   2. Writes minimal build_config.h / buildflag.h that pdfium expects (would
#      normally be generated by gn).
#   3. Patches a handful of platform-specific files (immediate_crash.h trap
#      sequence, ICU stub headers, libjpeg/zlib/libpng symlinks).
#   4. Compiles pdfium's render-path subset to libpdfium.a via direct em++.
#   5. Links src/pdfium/renderer.cpp against libpdfium.a + shared deps.
#
# Outputs: ${OUT}/pdfium/pdfium.{js,wasm}

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "${HERE}/.." && pwd)"
OUT="${OUT:-${ROOT}/out}"
SRC_DIR="${SRC_DIR:-/src}"

. "${HERE}/build-deps.sh"

# pdfium uses freetype, libjpeg, openjpeg, lcms2, libpng, zlib via system
# headers — make sure they exist before we touch pdfium.
ensure_zlib
ensure_libpng
ensure_freetype
ensure_libjpeg
ensure_openjpeg
ensure_lcms2

PDFIUM_REF="${PDFIUM_REF:-${PDFIUM_BRANCH:-main}}"
ABSEIL_REF="${ABSEIL_REF:-HEAD}"
FAST_FLOAT_REF="${FAST_FLOAT_REF:-HEAD}"

PDFIUM_SRC="${SRC_DIR}/pdfium"

# ---- Phase 1: fetch pdfium source + abseil + fast_float --------------------
clone_pinned "${PDFIUM_SRC}" https://pdfium.googlesource.com/pdfium.git \
    "${PDFIUM_REF}"
PDFIUM_COMMIT="$(git -C "${PDFIUM_SRC}" rev-parse HEAD)"

ABSEIL_SRC="${PDFIUM_SRC}/third_party/abseil-cpp"
clone_pinned "${ABSEIL_SRC}" \
    https://github.com/abseil/abseil-cpp.git "${ABSEIL_REF}"
ABSEIL_COMMIT="$(git -C "${ABSEIL_SRC}" rev-parse HEAD)"
FAST_FLOAT_SRC="${PDFIUM_SRC}/third_party/fast_float/src"
clone_pinned "${FAST_FLOAT_SRC}" \
    https://github.com/fastfloat/fast_float.git "${FAST_FLOAT_REF}"
FAST_FLOAT_COMMIT="$(git -C "${FAST_FLOAT_SRC}" rev-parse HEAD)"

PDFIUM_SOURCE_FINGERPRINT="pdfium=${PDFIUM_COMMIT};fast_float=${FAST_FLOAT_COMMIT};abseil=${ABSEIL_COMMIT}"
PDFIUM_SOURCE_STAMP="${WASM_PREFIX}/lib/libpdfium.source"

# ---- Phase 2: writes the gn-generated headers -----------------------------
mkdir -p "${PDFIUM_SRC}/build"
cat > "${PDFIUM_SRC}/build/buildflag.h" <<'EOF'
#ifndef BUILD_BUILDFLAG_H_
#define BUILD_BUILDFLAG_H_
#define BUILDFLAG_CAT_INDIRECT(a, b) a ## b
#define BUILDFLAG_CAT(a, b) BUILDFLAG_CAT_INDIRECT(a, b)
#define BUILDFLAG(flag) (BUILDFLAG_CAT(BUILDFLAG_INTERNAL_, flag)())
#endif
EOF
cat > "${PDFIUM_SRC}/build/build_config.h" <<'EOF'
#ifndef BUILD_BUILD_CONFIG_H_
#define BUILD_BUILD_CONFIG_H_
#include "build/buildflag.h"
#define OS_LINUX 1
#define OS_POSIX 1
#define BUILDFLAG_INTERNAL_IS_LINUX() (1)
#define BUILDFLAG_INTERNAL_IS_POSIX() (1)
#define BUILDFLAG_INTERNAL_IS_APPLE() (0)
#define BUILDFLAG_INTERNAL_IS_MAC() (0)
#define BUILDFLAG_INTERNAL_IS_IOS() (0)
#define BUILDFLAG_INTERNAL_IS_WIN() (0)
#define BUILDFLAG_INTERNAL_IS_ANDROID() (0)
#define BUILDFLAG_INTERNAL_IS_FUCHSIA() (0)
#define BUILDFLAG_INTERNAL_IS_CHROMEOS() (0)
#define BUILDFLAG_INTERNAL_IS_BSD() (0)
#define ARCH_CPU_WASM_FAMILY 1
#define ARCH_CPU_WASM 1
#define ARCH_CPU_32_BITS 1
#define ARCH_CPU_LITTLE_ENDIAN 1
#define COMPILER_CLANG 1
#define WCHAR_T_IS_32_BIT 1
#define BUILDFLAG_INTERNAL_PDF_ENABLE_V8() (0)
#define BUILDFLAG_INTERNAL_PDF_ENABLE_XFA() (0)
#define BUILDFLAG_INTERNAL_PDF_ENABLE_XFA_BMP() (0)
#define BUILDFLAG_INTERNAL_PDF_ENABLE_XFA_GIF() (0)
#define BUILDFLAG_INTERNAL_PDF_ENABLE_XFA_PNG() (0)
#define BUILDFLAG_INTERNAL_PDF_ENABLE_XFA_TIFF() (0)
#define BUILDFLAG_INTERNAL_PDF_USE_SKIA() (0)
#define BUILDFLAG_INTERNAL_PDF_USE_PARTITION_ALLOC() (0)
#define BUILDFLAG_INTERNAL_IS_ASMJS() (0)
#define BUILDFLAG_INTERNAL_IS_NACL() (0)
#define BUILDFLAG_INTERNAL_USE_PARTITION_ALLOC() (0)
#define BUILDFLAG_INTERNAL_USE_PARTITION_ALLOC_AS_MALLOC() (0)
#define BUILDFLAG_INTERNAL_ENABLE_BACKUP_REF_PTR_SUPPORT() (0)
#define BUILDFLAG_INTERNAL_ENABLE_DANGLING_RAW_PTR_CHECKS() (0)
#define BUILDFLAG_INTERNAL_USE_RAW_PTR_ASAN_UNOWNED_IMPL() (0)
#endif
EOF

# ---- Phase 3: patches ------------------------------------------------------
# wasm has no native trap, so immediate_crash.h's #error fires. Substitute
# __builtin_trap() (which clang lowers to wasm `unreachable`).
if grep -q "^#error No supported trap sequence!" \
        "${PDFIUM_SRC}/core/fxcrt/immediate_crash.h"; then
    sed -i 's|^#error No supported trap sequence!|#define TRAP_SEQUENCE1_() __builtin_trap()\n#define TRAP_SEQUENCE2_() ((void)0)|' \
        "${PDFIUM_SRC}/core/fxcrt/immediate_crash.h"
fi

# ICU stub: pdfium/core uses 7 u_* functions, all with wctype.h equivalents.
mkdir -p "${PDFIUM_SRC}/third_party/icu/source/common/unicode"
cat > "${PDFIUM_SRC}/third_party/icu/source/common/unicode/uchar.h" <<'EOF'
#ifndef PDFIUM_ICU_STUB_UCHAR_H_
#define PDFIUM_ICU_STUB_UCHAR_H_
#include <wctype.h>
#include <stdint.h>
#define u_islower(c) iswlower((wint_t)(c))
#define u_isupper(c) iswupper((wint_t)(c))
#define u_isalpha(c) iswalpha((wint_t)(c))
#define u_isalnum(c) iswalnum((wint_t)(c))
#define u_isspace(c) iswspace((wint_t)(c))
#define u_tolower(c) ((int32_t)towlower((wint_t)(c)))
#define u_toupper(c) ((int32_t)towupper((wint_t)(c)))
#endif
EOF

# Symlinks so pdfium's third_party/{libjpeg,zlib,libpng} include paths
# resolve to the system headers we built earlier.
mkdir -p "${PDFIUM_SRC}/third_party/libjpeg" \
         "${PDFIUM_SRC}/third_party/zlib" \
         "${PDFIUM_SRC}/third_party/libpng"
for h in jpeglib.h jconfig.h jerror.h jmorecfg.h jpegint.h; do
    ln -sf "${WASM_PREFIX}/include/$h" "${PDFIUM_SRC}/third_party/libjpeg/$h"
done
for h in zlib.h zconf.h; do
    ln -sf "${WASM_PREFIX}/include/$h" "${PDFIUM_SRC}/third_party/zlib/$h"
done
for h in png.h pngconf.h pnglibconf.h; do
    ln -sf "${WASM_PREFIX}/include/$h" "${PDFIUM_SRC}/third_party/libpng/$h"
done

# ---- Phase 4: compile libpdfium.a -----------------------------------------
if [ ! -f "${WASM_PREFIX}/lib/libpdfium.a" ] || \
        [ "$(cat "${PDFIUM_SOURCE_STAMP}" 2>/dev/null || true)" != "${PDFIUM_SOURCE_FINGERPRINT}" ]; then
    cd "${PDFIUM_SRC}"
    # `-DPDF_USE_AGG` opts into pdfium's in-tree AGG software rasterizer
    # (the only render backend we have — Skia is disabled). Without it,
    # core/fxge/cfx_defaultrenderdevice.h hides AttachAggImpl/CreateAgg
    # behind `#if defined(PDF_USE_AGG)` and core/fxge/dib/cfx_dibitmap.h
    # hides CompositeRect, so the out-of-line definitions in
    # core/fxge/agg/cfx_agg_devicedriver.cpp fail to match any declaration.
    export PDFIUM_CXXFLAGS="-O2 -fno-exceptions --std=c++20 -DNDEBUG \
        -DUSE_SYSTEM_LIBPNG -DUSE_SYSTEM_ZLIB -DUSE_SYSTEM_LIBOPENJPEG2 \
        -DUSE_SYSTEM_LCMS2 \
        -DPDF_USE_AGG \
        -I${PDFIUM_SRC} -I${PDFIUM_SRC}/public \
        -I${PDFIUM_SRC}/third_party/abseil-cpp \
        -I${WASM_PREFIX}/include \
        -I${WASM_PREFIX}/include/freetype2 \
        -I${WASM_PREFIX}/include/openjpeg-2.5"

    # pdfium main grew a font subsetter (core/fpdfapi/edit/cpdf_fontsubsetter.cpp)
    # that #includes <hb-subset.h>. We don't ship libharfbuzz in the wasm
    # sysroot — and we don't need to: it sits behind the PDF-edit/save APIs
    # the renderer never calls, so the linker would GC the symbols anyway.
    # Discover every .cc/.cpp/.c file that pulls in an `<hb…>` header and
    # drop them from the compile list. List is allowed to be empty (older
    # pdfium revisions had no such files).
    HB_SKIP="${PDFIUM_SRC}/.hb-skip"
    { grep -lrE '^[[:space:]]*#include[[:space:]]+<hb' \
        core constants fpdfsdk 2>/dev/null \
        | grep -E '\.(cc|cpp|c)$' \
        | sort -u; } > "${HB_SKIP}" || true
    HB_SKIP_COUNT=$(wc -l < "${HB_SKIP}" | tr -d ' ')
    [ "${HB_SKIP_COUNT}" -gt 0 ] && \
        echo "pdfium: skipping ${HB_SKIP_COUNT} harfbuzz-dependent source(s):" && \
        sed 's/^/  /' "${HB_SKIP}"

    # core/fxcodec/brotli/* is excluded for the same reason as the harfbuzz
    # sources above: pdfium main grew a BrotliDecode stream filter whose only
    # source, brotli_decoder.cpp, #includes the gn-vendored
    # third_party/brotli/include/brotli/decode.h — a tree our gclient-less
    # clone never fetches. We don't ship libbrotli in the wasm sysroot and
    # don't need to: the filter's sole call site in fpdf_parser_decode.cpp is
    # behind `#if defined(PDF_ENABLE_BROTLI)`, which our build_config.h never
    # defines, so nothing references BrotliDecoder and the linker would GC it
    # anyway. (brotli_decoder.h itself is a plain internal header with no
    # third_party include, so dropping just the .cpp is safe.)
    mapfile -t SRCS < <(find core constants fpdfsdk \
        third_party/agg23 third_party/bigint third_party/pdfium_base \
        \( -name "*.cc" -o -name "*.cpp" -o -name "*.c" \) \
        ! -name "*_unittest.*" ! -name "*_embeddertest.*" ! -name "*_test.*" \
        ! -name "*_fuzzer.*" ! -name "fuzzer_*.*" \
        ! -name "test_*.*" ! -name "*_test_helpers.*" \
        ! -name "*_windows.*" ! -name "*windowsrenderdevice*" \
        ! -name "fpdf_view_c_api_test.c" \
        ! -path "*/test/*" ! -path "*/testing/*" ! -path "*/tests/*" \
        ! -path "*/win32/*" ! -path "*/win/*" ! -path "*/apple/*" \
        ! -path "*/cocoa/*" ! -path "*/android/*" \
        ! -path "*/skia/*" ! -path "*/xfa/*" ! -path "*/fxjs/*" \
        ! -path "*/formfiller/*" ! -path "*/pwl/*" ! -path "*/fpdfxfa/*" \
        ! -path "core/fxge/skrifa/*" \
        ! -path "core/fxcodec/bmp/*" ! -path "core/fxcodec/gif/*" \
        ! -path "core/fxcodec/png/*" ! -path "core/fxcodec/tiff/*" \
        ! -path "core/fxcodec/brotli/*" \
        ! -name "progressive_decoder.cpp" \
        ! -name "*_progressive_decoder.cpp" \
        ! -name "code_point_view.cpp" \
        ! -name "fx_memory_pa.cpp" \
        2>/dev/null | sort | grep -vFxf "${HB_SKIP}")

    # Abseil ships a handful of out-of-line runtime-support functions that its
    # otherwise header-only facilities fall back on. pdfium's render subset
    # uses one such facility — core/fpdfapi/page/cpdf_sampledfunc.cpp holds its
    # sample inputs in an absl::InlinedVector — and because we build with
    # -fno-exceptions, InlinedVector's capacity-overflow path calls the
    # out-of-line absl::ThrowStdLengthError (absl/base/throw_delegate.cc)
    # rather than `throw`. That fallback in turn expands ABSL_RAW_LOG(FATAL, …)
    # to absl::raw_log_internal::RawLog (absl/base/internal/raw_logging.cc).
    # Both are ordinary (non-template) functions, so header inclusion can't
    # synthesize them, and our gclient-less clone — which never compiles abseil,
    # it only points -I at abseil's headers — leaves them undefined at the final
    # renderer link (wasm-ld: undefined symbol: absl::ThrowStdLengthError).
    # Compile exactly these two support TUs into libpdfium.a; every other bit of
    # abseil pdfium reaches lives in inline/template code the compiler emits
    # on demand. Locate them by filename rather than a fixed path because abseil
    # relocates them between revisions — throw_delegate.cc moved from
    # absl/base/internal/ up to absl/base/ in mid-2026, which is the move that
    # first broke this build.
    mapfile -t ABSL_SUPPORT < <(find third_party/abseil-cpp/absl \
        \( -name "throw_delegate.cc" -o -name "raw_logging.cc" \) \
        ! -path "*/testing/*" 2>/dev/null | sort)
    if [ "${#ABSL_SUPPORT[@]}" -ne 2 ]; then
        echo "pdfium: ERROR: expected abseil throw_delegate.cc + raw_logging.cc," \
             "found ${#ABSL_SUPPORT[@]}: ${ABSL_SUPPORT[*]:-<none>}" >&2
        echo "pdfium: (abseil likely renamed or relocated them again — update" \
             "the find above to match)" >&2
        exit 1
    fi
    echo "pdfium: adding ${#ABSL_SUPPORT[@]} abseil support source(s):"
    printf '  %s\n' "${ABSL_SUPPORT[@]}"
    SRCS+=("${ABSL_SUPPORT[@]}")

    echo "pdfium: ${#SRCS[@]} sources to compile"
    mkdir -p obj

    run_one() {
        local src="$1"
        local out="obj/$(echo "$src" | tr / _ \
            | sed -e 's/\.cc$/.o/' -e 's/\.cpp$/.o/' -e 's/\.c$/.o/')"
        local cmd cflags
        case "$src" in
            *.c)  cmd=emcc; cflags="${PDFIUM_CXXFLAGS//--std=c++20/}" ;;
            *)    cmd=em++; cflags="${PDFIUM_CXXFLAGS}" ;;
        esac
        if ! $cmd $cflags -c -o "$out" "$src" 2>"$out.err"; then
            echo "==== first failure: $src ===="
            cat "$out.err"
            return 1
        fi
        rm -f "$out.err"
    }
    export -f run_one
    export PDFIUM_CXXFLAGS

    fail=0
    printf '%s\n' "${SRCS[@]}" \
        | xargs -P "$(nproc)" -I{} bash -c 'run_one "$1" || exit 255' _ {} \
        || fail=1
    [ "$fail" -eq 0 ] || exit 1

    emar rcs "${WASM_PREFIX}/lib/libpdfium.a" obj/*.o
    # Pre-clean the destination so headers removed upstream don't linger.
    rm -rf "${WASM_PREFIX}/include/pdfium-public"
    mkdir -p "${WASM_PREFIX}/include/pdfium-public"
    cp -r public/* "${WASM_PREFIX}/include/pdfium-public/"
    printf '%s\n' "${PDFIUM_SOURCE_FINGERPRINT}" > "${PDFIUM_SOURCE_STAMP}"
    echo "pdfium: libpdfium.a installed"
fi

# ---- Phase 5: build the renderer wasm -------------------------------------
mkdir -p "${OUT}/pdfium"

PKG_DEPS="libpng freetype2 libopenjp2 libjpeg lcms2 zlib"
CFLAGS="$(renderer_pkg_cflags ${PKG_DEPS})"
LIBS="$(renderer_pkg_libs ${PKG_DEPS}) -lpdfium"

em++ -o "${OUT}/pdfium/pdfium.js" \
    "${ROOT}/src/pdfium/renderer.cpp" \
    --std=c++20 \
    ${CFLAGS} \
    -I"${ROOT}/src/common" \
    -I"${WASM_PREFIX}/include/pdfium-public" \
    ${LIBS} \
    $(renderer_emcc_flags) \
    -s EXPORT_NAME="'PdfiumRenderer'" \
    -s NO_FILESYSTEM=1 \
    -s EXPORTED_FUNCTIONS='["_render","_num_pages","_malloc","_free"]' \
    -s EXPORTED_RUNTIME_METHODS='["HEAPU8","writeArrayToMemory"]' \
    -DNDEBUG \
    -flto \
    -O3 -msimd128 -msse -fno-exceptions \
    --js-library "${ROOT}/src/common/myjs.js"

finalize_renderer_output "${OUT}/pdfium/pdfium.js"

cat > "${OUT}/pdfium/source.json" <<EOF
{
  "name": "pdfium",
  "repo": "https://pdfium.googlesource.com/pdfium.git",
  "ref": "${PDFIUM_REF}",
  "commit": "${PDFIUM_COMMIT}",
  "dependencies": {
    "abseil": {
      "repo": "https://github.com/abseil/abseil-cpp.git",
      "ref": "${ABSEIL_REF}",
      "commit": "${ABSEIL_COMMIT}"
    },
    "fast_float": {
      "repo": "https://github.com/fastfloat/fast_float.git",
      "ref": "${FAST_FLOAT_REF}",
      "commit": "${FAST_FLOAT_COMMIT}"
    }
  },
  "fingerprint": "${PDFIUM_SOURCE_FINGERPRINT}"
}
EOF
